apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: interns-rolebinding
  namespace: instavote
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: interns-role
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: interns
    namespace: instavote
