apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: interns-role
  namespace: instavote
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
