# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  cpus_per_node = 8
  mem_per_node = 2048

  config.vm.define "atomic_host", primary: true do |atomic|
		atomic.vm.box = "fedora/28-atomic-host"
		atomic.vm.hostname = 'atomic'
		atomic.vm.network "private_network", bridge: "MySwitch"
		atomic.vm.provider "hyperv" do |hv|
			hv.vmname = "atomic_host"	
			hv.cpus = cpus_per_node
			hv.memory = mem_per_node
		end
	end
end
