# -*- mode: ruby -*-
# vi: set ft=ruby :

# Creates an environment with a variable number of nodes, each visible in the private subnetwork.
# Node 1 is supposed to be the master, the others are the workers.
# All the nodes are based on Ubuntu 22.04 LTS and the Hyper-V hypervisor.
# For a static IP on Hyper-V, we also need to create an ad-hoc hyper-v virtual switch.
# Please read the Powershell script in ./scripts/create-nat-hyperv-switch.ps1
# Requires the vagrant-reload plugin:
#   Install globally with: vagrant plugin install vagrant-reload
# Otherwise it will be installed locally each time you create the environments.

# Maintainer: Renato Perini <renato.perini@gmail.com>

Vagrant.require_version ">= 2.4.9"

Vagrant.configure(2) do |config| 
	
	# Config parameters for the environments
	number_of_nodes = 6
	cpus_per_node = 16
	mem_per_node = 4192
	machine_name_prefix = "node"
	machine_internal_domain = "vmstar.lan"
	regular_user = "user"
	regular_password = "user"
	root_password = "vagrant"
	update_distro = "full" # release = do-release-upgrade, full = apt full upgrade, upgrade = apt upgrade, disabled = apt update
	enable_zsh = false
	enable_docker = false
	# enable_kubernetes = true subdivides the total number of nodes in 1 load balancer node and 3 control plane nodes. The remaining nodes
	# are worker nodes. So if you choose, for example, number_of_nodes = 6, it will create 1 load balancer with 1GB of RAM,
	# 3 control plane nodes and 2 worker nodes. Make sure number_of_nodes in this case is always bigger than 4. Memory and CPUs for 
	# these spacial nodes are fixed: 1024M / 3 vCPUs for the load balancer, 2048M / 4 vCPUs for the control plane nodes. The worker nodes
	# are associated with mem_per_node amount and cpus_per_node. The load balancer node will install (and configure) an HAProxy instance 
	# while it will be installed Kubernetes through MicroK8s / snapd on the other nodes. 
	# If enable_kubernetes = false, the nodes will be created all equal following the specs given with the cpus_per_node and mem_per_node parameters.
	enable_kubernetes = true
	kubernetes_version = '1.32'
	# An additional rancher node is created as the second VM. In this node it is not necessary to provision metallb.
	# This node will be added to the dnsmasq DNS server with the name rancher2
	enable_rancher2_node = false
	extra_hosts = ["argocd", "nginx-ingress", "nginx-gateway"]
	# Working with snap in scripts is a pain. So we don't bother restarting things. If you have problems, enable a final reboot.
	enable_final_reboot = true
	enable_nfs = true
	enable_java = false
	java_versions = ["21", "25"]
	java_flavors = ["jdk", "graalvm"] # jdk for eclipse temurin, graalvm for official graalvm. You can choose both.
	enable_gitea = false
	enable_synced_folder = false
	smb_user = ""
	smb_pass = ""
	
	# Require some plugins.
	config.vagrant.plugins = ["vagrant-reload"]

	# Don't bother with SSH
	config.ssh.keep_alive = true
	config.ssh.forward_agent = true
	config.ssh.forward_x11 = true

	# Enable /etc/hosts handling automatically.
	if Vagrant.has_plugin?("vagrant-hostmanager")
		config.hostmanager.enabled = false
		config.hostmanager.manage_host = false
		config.hostmanager.manage_guest = true
		config.hostmanager.ignore_private_ip = true
		config.hostmanager.include_offline = true
    end

	# Define a start trigger.
	config.trigger.before :up do |trigger|
		trigger.info = "Creating 'LabSwitch' Hyper-V switch if it does not exist..."
		trigger.run = {
			privileged: "true", powershell_elevated_interactive: "true", path: "./scripts/powershell/create-nat-hyperv-switch.ps1"
		}
	end

    # Compute the hostnames.
    hostnames = (1..number_of_nodes).map do |i|
        # Simple case: Kubernetes is not activated
        unless enable_kubernetes
            next "#{machine_name_prefix}-#{i}"
        end
        # Kubernetes active -> two distinct scenarios
        if enable_rancher2_node
            case i
            when 1
                "#{machine_name_prefix}-lb"
            when 2
                "#{machine_name_prefix}-rancher"
            when 3..5
                "#{machine_name_prefix}-master#{i - 2}"
            else
                "#{machine_name_prefix}-worker#{i - 5}"
            end
        else
            case i
            when 1
                "#{machine_name_prefix}-lb"
            when 2..4
                "#{machine_name_prefix}-master#{i - 1}"
            else
                "#{machine_name_prefix}-worker#{i - 4}"
            end
        end
    end

	# Provision the nodes.
	(1..number_of_nodes).each do |i|
        config.vm.define "#{machine_name_prefix}-#{i}", primary: (i == 1) do |node|
            node.vm.network "public_network", bridge: "LabSwitch"
	    	node.vm.box = "generic/ubuntu2204"
            node.vm.hostname = "#{hostnames[i - 1]}.#{machine_internal_domain}"
	    	node.vm.provider "hyperv" do |hyperv|
	    		hyperv.enable_virtualization_extensions = true
        		hyperv.linked_clone = true
                # LOGICA DI ASSEGNAZIONE CPU/RAM
                if enable_kubernetes
                    if enable_rancher2_node
                        # Kubernetes + Rancher2
                        case i
                        when 1
                            hyperv.cpus   = 3
                            hyperv.memory = 1024
                        when 2
                            hyperv.cpus   = 4
                            hyperv.memory = 4096
                        when 3, 4, 5
                            hyperv.cpus   = 4
                            hyperv.memory = 2048
                        else
                            hyperv.cpus   = cpus_per_node
                            hyperv.memory = mem_per_node
                        end
                    else
                        # Solo Kubernetes
                        case i
                        when 1
                            hyperv.cpus   = 3
                            hyperv.memory = 1024
                        when 2, 3, 4
                            hyperv.cpus   = 4
                            hyperv.memory = 2048
                        else
                            hyperv.cpus   = cpus_per_node
                            hyperv.memory = mem_per_node
                        end
                    end
                else
                    # Kubernetes disattivato → tutto default
                    hyperv.cpus   = cpus_per_node
                    hyperv.memory = mem_per_node
                end

				hyperv.vmname = "#{machine_name_prefix}-#{i}"
				hyperv.maxmemory = 0
	    	end

            # Configure Network with a static IP.
            node.vm.provision "shell", path: "./scripts/bash/network_setup.sh" do |s|
                s.args = "#{i}"
            end

			# Update the distro
            node.vm.provision "shell", path: "./scripts/bash/update_distro.sh" do |s|
			    s.args = "#{update_distro}"
			end

            # After an apt-get upgrade or dist-upgrade, do a reload
            if update_distro != "disabled"
                node.vm.provision "reload"
            end

            if update_distro == "release"
                node.vm.provision "shell", path: "./scripts/bash/release_upgrade_distro.sh" do |s|
                    s.args = "#{update_distro}"
                end
                node.vm.provision "reload"
            end

	    	# Install basic software.
			node.vm.provision "shell", path: "./scripts/bash/basic_software_provision.sh"
			# Provisioner finale di pulizia
            node.vm.provision "shell", inline: <<-SHELL
                set -euo pipefail
                echo "[INFO] Cleanup after release upgrade..."
                apt-get autoremove --purge -qq -y && apt-get autoclean -qq -y && apt-get clean -qq -y
                # After installation of packages, the /etc/hosts file might contain some unwanted lines. We reset them.
                echo "[INFO] Resetting /etc/hosts file ..."
                if [ -s /etc/hosts ]; then
                    sed -i '1s/.*/127.0.0.1 localhost/' /etc/hosts
                else
                    echo '127.0.0.1 localhost' > /etc/hosts
                fi
            SHELL

			# Install Docker
			if enable_docker == true then
	    		node.vm.provision "shell", path: "./scripts/bash/docker_provision.sh"
			end

			# Install ZSH, Oh-My-ZSH, Powerline10k, Dracula Theme for tmux
			if enable_zsh == true then
				node.vm.provision "shell", path: "./scripts/bash/zsh_provision.sh"
			end

            # Mixed actions, mostly unrelated to each other.
			node.vm.provision "shell", path: "./scripts/bash/misc_provision.sh"

			# We want a normal user. With Bash or ZSH if available.
	    	node.vm.provision "shell", path: "./scripts/bash/add_sudo_user.sh" do |s|
	    		s.args = ["#{regular_user}", "#{regular_password}", "#{root_password}"]
	    	end
            
			# Provision dnsmasq server in the first node and configure split dns on systemd-resolved on the others
			node.vm.provision "shell", path: "./scripts/bash/dnsmasq_provision.sh" do |s|
                s.args = ["#{i}", hostnames.join(","), "#{machine_internal_domain}", "#{enable_rancher2_node}", "#{extra_hosts.join(",")}"]
			end

			# Provision HAProxy in the first node if enable_kubernetes is enabled.
            if enable_kubernetes == true && i == 1
				# Provision HAProxy
                node.vm.provision "shell", path: "./scripts/bash/haproxy_provision.sh" do |s|
					# If enable_kubernetes is set and we're on the first node, provision HAProxy
					s.args = ["#{i}", "#{enable_kubernetes}"]
				end
			end

			# Provision Kubernetes through MicroK8S. Provisioning occurs from node 2 onwards.
            if enable_kubernetes == true && i >= 2
                node.vm.provision "shell", path: "./scripts/bash/microk8s_provision.sh" do |s|
					s.args = ["#{i}", "#{kubernetes_version}", "#{enable_rancher2_node}"]
				end
			end

			# Enable Java Development Kit (JDK 17 from the Eclipse Temurin Project)
			if enable_java == true then
                node.vm.provision "shell", path: "./scripts/bash/java_provision.sh"
			end

			# Provision NFS Server / Clients
			if enable_nfs == true then
                node.vm.provision "shell", path: "./scripts/bash/nfs_provision.sh" do |s|
					# If enable_kubernetes == true, we enable the NFS server only starting from first control plane node.
					s.args = ["#{i}", "#{enable_kubernetes}", "#{enable_rancher2_node}"]
				end
			end

			# Provision the Gitea Git Server
			if enable_gitea == true then
				node.vm.provision "shell", path: "./scripts/bash/gitea_provision.sh" do |s|
					s.args = "#{i}"
				end
			end
	    	
			# Enable synced folder. Be sure to fill in the administrative username and password of your Windows account.
			if enable_synced_folder == true then
	    		node.vm.synced_folder "./#{machine_name_prefix}_#{i}", "/vagrant", create: true, type: "smb",
	    			smb_password: "#{smb_pass}", smb_username: "#{smb_user}"
	    	else
				# Or disable synced folder
				node.vm.synced_folder ".", "/vagrant", disabled: true	
			end

            # Enable a final reboot.
            if enable_final_reboot == true then
                 node.vm.provision "shell", inline: <<-SHELL
                    echo -e "\e[32m>>> User chose to do a final reboot. Rebooting ... \e[0m"
                 SHELL
                node.vm.provision "reload"
            end
	    end		
	end
end
