apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    role: redis
    tier: back
  namespace: instavote
spec:
  selector:
    app: redis
  ports:
    - name: redis-db
      port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
  
