Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Outside"
  
    (1..2).each do |i|
        config.vm.define "web_#{i}" do |web|
            web.vm.box = "generic/ubuntu2204"
            if i == 1 then
                web.vm.provision "shell", inline: "echo Web 1"
                web.vm.hostname = "web-lb"
            else
                web.vm.provision "shell", inline: "echo Web 2"
                web.vm.hostname = "web-worker"
            end
            web.vm.provider "hyperv" do |hyperv|
                hyperv.enable_virtualization_extensions = true
                hyperv.linked_clone = true	
                hyperv.maxmemory = nil
                if i == 1 then
                    hyperv.vmname = "web-lb"
                    hyperv.memory = 1024
                    hyperv.cpus = 4
                else 
                    hyperv.vmname = "web-worker"
                    hyperv.memory = 2048
                    hyperv.cpus = 8
                end
            end
        end
    end
end