# -*- mode: ruby -*-
# vi: set ft=ruby :

# Creates an environment with a variable number of nodes, each visible in the private subnetwork.
# Node 1 is supposed to be the master, the others are the workers.
# All the nodes are based on AlmaLinux 9 and the Hyper-V hypervisor.
# Requires the vagrant-hostmanager plugin:
# 	Install globally with: vagrant plugin install vagrant-hostmanager beforehand.

# For a static IP on Hyper-V, we also need to create an ad-hoc hyper-v virtual switch.
# Please read the Powershell script in ./scripts/create-nat-hyperv-switch.ps1
# Requires the vagrant-reload plugin:
#   Install globally with: vagrant plugin install vagrant-reload
# Otherwise it will be installed locally each time you create the environments.

# Maintainer: Renato Perini <renato.perini@gmail.com>

Vagrant.require_version ">= 2.2.19"

# Provisioning stuff we don't want to put in the ./scripts/bash/provision.sh script.
$script = <<-SCRIPT
#!/usr/bin/env bash

echo "Updating neofetch ..."
curl -s https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch -o /usr/bin/neofetch
chmod +x /usr/bin/neofetch
echo "neofetch --ascii_distro AlmaLinux" | tee -a $HOME/.bash_profile | tee -a /home/vagrant/.bash_profile
echo "Installing Docker Bash completion ..."
curl https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker -o /etc/bash_completion.d/docker.sh
echo "Disabling SELinux ..."
setenforce 0
sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
echo "Enabling X11 Forwarding request for SSH ..."
sed -i --follow-symlinks 's/\#AddressFamily any/AddressFamily inet/g' /etc/ssh/sshd_config
echo "Disabling Firewalld ..."
systemctl disable --now firewalld

SCRIPT

Vagrant.configure(2) do |config| 
	
	# Config parameters for the environments
	number_of_nodes = 2
	cpus_per_node = 4
	mem_per_node = 4096
	machine_name_prefix = "portainer"
	regular_user = ""
	regular_password = ""
	provision_docker = false
	enable_synced_folder = false
	smb_user = ""
	smb_pass = ""
	
	# Require some plugins.
	config.vagrant.plugins = ["vagrant-hostmanager","vagrant-reload"]

	# Enable /etc/hosts handling automatically.
	if Vagrant.has_plugin?("vagrant-hostmanager")
		config.hostmanager.enabled = true
		config.hostmanager.manage_host = false
		config.hostmanager.manage_guest = true
		config.hostmanager.ignore_private_ip = false
		config.hostmanager.include_offline = true
    end

	# Define a start trigger.
	config.trigger.before :up do |trigger|
		trigger.info = "Creating 'LabSwitch' Hyper-V switch if it does not exist..."
		trigger.run = {
			privileged: "true", powershell_elevated_interactive: "true", path: "./scripts/powershell/create-nat-hyperv-switch.ps1"
		}
	end

	# Provision the nodes.
	(1..number_of_nodes).each do |i|
        config.vm.define "#{machine_name_prefix}_#{i}", primary: true do |master|
	    	master.vm.box = "almalinux/9"
	    	master.vm.hostname = "#{machine_name_prefix}#{i}"
	    	master.vm.provider "hyperv" do |hyperv|
	    		hyperv.enable_virtualization_extensions = true
        		hyperv.linked_clone = true
	    		hyperv.vmname = "#{machine_name_prefix}_#{i}"	
	    		hyperv.cpus = cpus_per_node
	    		hyperv.memory = mem_per_node
	    	end
                    
	    	# Define a reload trigger.
	    	master.trigger.before :reload do |trigger|
	    		trigger.info = "Setting Hyper-V switch to 'LabSwitch' to allow for static IP..."
	    		trigger.run = {
	    			privileged: "true", powershell_elevated_interactive: "true", path: "./scripts/powershell/set-hyperv-switch.ps1", args: "#{machine_name_prefix}_#{i}"
	    		}
	    	end
    
	    	# Provision some stuff.
			if provision_docker == true then
	    		master.vm.provision "shell", path: "./scripts/bash/docker_provision.sh"
			end
	    	master.vm.provision "shell", inline: $script
	    	master.vm.provision "shell", path: "./scripts/bash/add-sudo-user.sh" do |s|
	    		s.args = ["#{regular_user}", "#{regular_password}"]
	    	end
	    	master.vm.provision "shell", path: "./scripts/bash/configure-static-ip.sh" do |s|
	    		s.args = "#{i}"
	    	end
	    			
	    	# Reload the machine.
	    	master.vm.provision :reload
    
	    	
			if enable_synced_folder == true then
	    		# Enable synced folder. Be sure to fill in the administrative username and password of your Windows account.
	    		master.vm.synced_folder "./#{machine_name_prefix}_#{i}", "/vagrant", create: true, type: "smb",
	    			smb_password: "#{smb_pass}", smb_username: "#{smb_user}"
	    	else
				# Or disable synced folder
				master.vm.synced_folder ".", "/vagrant", disabled: true	
			end
	    end
	end
end
