# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	
	if Vagrant.has_plugin?("vagrant-hostmanager")
		config.hostmanager.enabled = true
		config.hostmanager.manage_host = false
		config.hostmanager.manage_guest = true
		config.hostmanager.ignore_private_ip = false
		config.hostmanager.include_offline = true
	end
		
	config.vm.define "ansible_master", primary: true do |master|
		master.vm.box = "centos/7"
		master.vm.hostname = 'master'
		master.vm.network "private_network", ip: "192.168.33.10"
		master.vm.provision "shell", inline: <<-SHELL
			yum -y update
			yum -y install vim ansible
		SHELL
		config.vm.provider "virtualbox" do |vb|
			vb.name = "ansible_master"
			vb.memory = "512"
			vb.cpus = 8
		end
	end
	
	config.vm.define "ansible_slave" do |slave|
		slave.vm.box = "centos/7"
		slave.vm.hostname = 'slave'
		slave.vm.network "private_network", ip: "192.168.33.11"
		slave.vm.provision "shell", inline: <<-SHELL
				yum -y update
				yum -y install vim
		SHELL
		config.vm.provider "virtualbox" do |vb|
			vb.name = "ansible_slave"
			vb.memory = "1024"
			vb.cpus = 8
		end
	end

end
