apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: jenkins.192.168.137.172.xip.io
    http:
      paths:
      - backend:
          serviceName: jenkins
          servicePort: http
        path: /
  - host: jenkins-agent.192.168.137.172.xip.io
    http:
      paths:
      - backend:
          serviceName: jenkins-agent
          servicePort: slavelistener
        path: /
